library(testthat)
source("inst/tests/test-pkgs.R")
source("R/correlatedsamplers.R")
source("R/generators.R")
source("R/missingness.R")
source("R/helpers.R")

test_file("inst/tests/test-generators.R")
test_file("inst/tests/test-correlatedsamplers.R")
test_file("inst/tests/test-missingness.R")